name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "0,15,30,45 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y tzdata
          yarn install --frozen-lockfile

      - name: Fetch Docs
        env:
          GOOGLE_OAUTH_CREDENTIALS: ${{secrets.GOOGLE_OAUTH_CREDENTIALS}}
          DRIVE_ACCESS_TOKEN: ${{secrets.DRIVE_ACCESS_TOKEN}}
        run: |
          mkdir docs/
          echo "$GOOGLE_OAUTH_CREDENTIALS" > credentials.json
          echo "$DRIVE_ACCESS_TOKEN" > token.json
          yarn docusaurus drive:sync

      - name: Build website
        env:
          TZ: "America/Los_Angeles"
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
